spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgress
    username: postgres
    url: jdbc:postgresql://localhost:5556/my_wh_inter
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
